// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKk1a6H65vQLO_nvPAPGKSY8SGVb5V2G8',
    appId: '1:720094966565:web:eeddb33e3b3a8f4b6ce0cc',
    messagingSenderId: '720094966565',
    projectId: 'fir-ce412',
    authDomain: 'fir-ce412.firebaseapp.com',
    storageBucket: 'fir-ce412.firebasestorage.app',
    measurementId: 'G-GJBMQQW16H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm0MEySY7s0b310ekw4BQSgMhRQEMioFM',
    appId: '1:720094966565:android:301cebf3176a645f6ce0cc',
    messagingSenderId: '720094966565',
    projectId: 'fir-ce412',
    storageBucket: 'fir-ce412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXxTFbe6nWvNWi-rj6fBgDYx6w29ySOps',
    appId: '1:720094966565:ios:bafc221860232e1b6ce0cc',
    messagingSenderId: '720094966565',
    projectId: 'fir-ce412',
    storageBucket: 'fir-ce412.firebasestorage.app',
    iosBundleId: 'com.example.waInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXxTFbe6nWvNWi-rj6fBgDYx6w29ySOps',
    appId: '1:720094966565:ios:bafc221860232e1b6ce0cc',
    messagingSenderId: '720094966565',
    projectId: 'fir-ce412',
    storageBucket: 'fir-ce412.firebasestorage.app',
    iosBundleId: 'com.example.waInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKk1a6H65vQLO_nvPAPGKSY8SGVb5V2G8',
    appId: '1:720094966565:web:e6e1e34ea4e134af6ce0cc',
    messagingSenderId: '720094966565',
    projectId: 'fir-ce412',
    authDomain: 'fir-ce412.firebaseapp.com',
    storageBucket: 'fir-ce412.firebasestorage.app',
    measurementId: 'G-GTDLZ8BZY4',
  );

}